apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argo-ingress
  namespace: argocd
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`argocd.home.arpa`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
