alloy:
  extraPorts:
    - name: grpc-otlp
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: http-otlp
      port: 4318
      targetPort: 4318
      protocol: TCP
  configMap:
    content: |-
      // -----------------------------------------------------------------------
      // Prometheus
      // https://grafana.com/docs/alloy/latest/collect/prometheus-metrics/
      // https://grafana.com/docs/alloy/latest/reference/components/discovery/discovery.relabel/
      // -----------------------------------------------------------------------

      discovery.kubernetes "pod_metrics" {
        role  = "pod"
      }

      discovery.relabel "pod_metrics" {
        targets = discovery.kubernetes.pod_metrics.targets

        rule {
          action        = "keep"
          source_labels = ["__meta_kubernetes_pod_container_name"]
          regex         = "istio-proxy"
        }

        rule {
          action        = "keep"
          source_labels = ["__meta_kubernetes_pod_annotation_prometheus_io_scrape"]
          regex         = "true"
        }

        rule {
          action        = "replace"
          source_labels = ["__meta_kubernetes_pod_ip", "__meta_kubernetes_pod_annotation_prometheus_io_port"]
          separator = ":"
          target_label  = "__address__"
        }

        rule {
          action        = "replace"
          source_labels = ["__meta_kubernetes_pod_annotation_prometheus_io_path"]
          target_label  = "__metrics_path__"
        }
      }

      prometheus.scrape "pod_metrics" {
        targets      = discovery.relabel.pod_metrics.output
        forward_to   = [prometheus.remote_write.default.receiver]
      }

      prometheus.remote_write "default" {
        endpoint {
          url = "http://prometheus.home.arpa/api/v1/write"
        }
      }

      // -----------------------------------------------------------------------
      // tempo configuration 
      // https://grafana.com/docs/alloy/latest/collect/opentelemetry-data/
      // https://grafana.com/docs/agent/latest/flow/reference/components/otelcol.exporter.otlphttp/
      // -----------------------------------------------------------------------

      //tracing {
      //  sampling_fraction = 1
      //  write_to = [otelcol.exporter.otlphttp.tempo.input]
      //}

      otelcol.receiver.otlp "tempo" {
        grpc {
          endpoint = "0.0.0.0:4317"
        }

        output {
          traces = [otelcol.exporter.otlphttp.tempo.input]
        }
      }

      otelcol.exporter.otlphttp "tempo" {
        client {
          endpoint = "http://tempo-otlp.home.arpa"
        }
      }

      // -----------------------------------------------------------------------
      // loki configuration
      // https://grafana.com/docs/alloy/latest/collect/logs-in-kubernetes/
      // -----------------------------------------------------------------------

      discovery.kubernetes "pod_logs" {
        role = "pod"
        selectors {
          role = "pod"
          field = "spec.nodeName=" + coalesce(sys.env("HOSTNAME"), constants.hostname)
        }
      }

      discovery.relabel "pod_logs" {
        targets = discovery.kubernetes.pod_logs.targets

        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          action = "replace"
          target_label = "namespace"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_name"]
          action = "replace"
          target_label = "pod"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_container_name"]
          action = "replace"
          target_label = "container"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
          action = "replace"
          target_label = "app"
        }

        rule {
          source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_pod_container_name"]
          action = "replace"
          target_label = "job"
          separator = "/"
          replacement = "$1"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_uid", "__meta_kubernetes_pod_container_name"]
          action = "replace"
          target_label = "__path__"
          separator = "/"
          replacement = "/var/log/pods/*$1/*.log"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_container_id"]
          action = "replace"
          target_label = "container_runtime"
          regex = "^(\\S+):\\/\\/.+$"
          replacement = "$1"
        }

        rule {
          source_labels = ["service_name", "__meta_kubernetes_namespace"]
          action = "replace"
          target_label = "service_name"
          separator = "."
          replacement = "$1"
        }
      }

      loki.source.kubernetes "pod_logs" {
        targets    = discovery.relabel.pod_logs.output
        forward_to = [loki.process.pod_logs.receiver]
      }

      loki.process "pod_logs" {
        stage.static_labels {
            values = {
              cluster = "example",
            }
        }

        forward_to = [loki.write.default.receiver]
      }

      loki.write "default" {
        endpoint {
          url = "http://loki.home.arpa/loki/api/v1/push"
        }
      }
