apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-ingress
  namespace: storage
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`minio-console.home.arpa`)
      kind: Rule
      services:
        - name: minio-console
          port: 9090
