apiVersion: v1
kind: Secret
metadata:
  name: forgejo-runner-secret
  namespace: forgejo
type: Opaque
stringData:
  FORGEJO_RUNNER_INSTANCE_URL: "http://forgejo.home.arpa"
  FORGEJO_RUNNER_REGISTRATION_TOKEN: "changeme"
