apiVersion: v1
kind: Secret
stringData:
  username: admin
  password: changeme
metadata:
  name: minio-admin-credentials-secret
  namespace: storage
type: Opaque
---
apiVersion: v1
kind: Secret
stringData:
  gitlab: |
    username=gitlab
    password=changeme
    disabled=false
    policies=gitlab-readwrite
    setPolicies=true
metadata:
  name: minio-gitlab-credentials-secret
  namespace: storage
type: Opaque
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: minio
  namespace: storage
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: minio
  targetNamespace: storage
  version: 17.0.21
  valuesContent: |-
    auth:
      existingSecret: minio-admin-credentials-secret
      rootUserSecretKey: username
      rootPasswordSecretKey: password
    persistence:
      size: 4Gi
      storageClass: local-path
    provisioning:
      enabled: true
      buckets:
        - name: gitlab-registry
        - name: gitlab-artifacts
        - name: gitlab-backups
        - name: gitlab-tmp
        - name: gitlab-ci-secure-files
        - name: gitlab-dependency-proxy
        - name: gitlab-external-diffs
        - name: gitlab-lfs
        - name: gitlab-packages
        - name: gitlab-terraform-state
        - name: gitlab-uploads
        - name: gitlab-pages
        - name: gitlab-runners-cache
      policies:
        - name: gitlab-readwrite
          statements:
            - resources:
                - "arn:aws:s3:::gitlab-registry/*"
                - "arn:aws:s3:::gitlab-artifacts/*"
                - "arn:aws:s3:::gitlab-backups/*"
                - "arn:aws:s3:::gitlab-tmp/*"
                - "arn:aws:s3:::gitlab-ci-secure-files/*"
                - "arn:aws:s3:::gitlab-dependency-proxy/*"
                - "arn:aws:s3:::gitlab-external-diffs/*"
                - "arn:aws:s3:::gitlab-lfs/*"
                - "arn:aws:s3:::gitlab-packages/*"
                - "arn:aws:s3:::gitlab-terraform-state/*"
                - "arn:aws:s3:::gitlab-uploads/*"
                - "arn:aws:s3:::gitlab-pages/*"
                - "arn:aws:s3:::gitlab-runners-cache/*"
              effect: "Allow"
              actions:
                - "s3:GetBucketLocation"
                - "s3:List*"
                - "s3:ListBucket"
                - "s3:GetObject"
                - "s3:PutObject"
                - "s3:DeleteObject"
      usersExistingSecrets:
        - minio-gitlab-credentials-secret
    image:
      repository: bitnamilegacy/minio
    clientImage:
      repository: bitnamilegacy/minio-client
    console:
      image:
        repository: bitnamilegacy/minio-object-browser
    defaultInitContainers:
      volumePermissions:
        image:
          repository: bitnamilegacy/os-shell
