apiVersion: v1
kind: Secret
stringData:
  password: changeme
metadata:
  name: redis-secret
  namespace: storage
type: Opaque
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: redis
  namespace: storage
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: redis
  targetNamespace: storage
  version: 24.0.8
  valuesContent: |-
    image:
      repository: bitnamilegacy/redis
    architecture: standalone
    auth:
      existingSecret: redis-secret
      existingSecretPasswordKey: password
