apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
---
apiVersion: v1
kind: Secret
stringData:
  password: changeme
metadata:
  name: keycloak-admin-credentials
  namespace: keycloak
type: Opaque
---
apiVersion: v1
kind: Secret
stringData:
  username: keycloak
  password: changeme
metadata:
  name: keycloak-db-credentials
  namespace: keycloak
type: Opaque
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: keycloak
  namespace: keycloak
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: keycloak
  targetNamespace: keycloak
  version: 25.2.0
  valuesContent: |-
    image:
      repository: bitnamilegacy/keycloak
    replicaCount: 1
    postgresql:
      enabled: false
    extraEnvVars:
      - name: PROXY_ADDRESS_FORWARDING
        value: "true"
      - name: PROXY_MODE
        value: "edge"
      - name: KEYCLOAK_FRONTEND_URL
        value: "https://keycloak.home.arpa"
      - name: KC_HOSTNAME
        value: "keycloak.home.arpa"
    httpRelativePath: "/"
    auth:
      adminUser: admin
      existingSecret: keycloak-admin-credentials
      passwordSecretKey: password
    externalDatabase:
      type: postgres
      host: postgres.storage.svc.cluster.local
      port: 5432
      database: keycloak
      schema: public
      existingSecret: "keycloak-db-credentials"
      existingSecretUserKey: "username"
      existingSecretPasswordKey: "password"
    logging:
      output: default
      level: INFO
