apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: v1
kind: Secret
stringData:
  clientSecret: "changeme"
metadata:
  name: argocd-oidc-secret
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
type: Opaque
---
apiVersion: v1
kind: Secret
stringData:
  redis-password: "changeme"
metadata:
  name: argocd-redis-secret
  namespace: argocd
type: Opaque
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: argocd
spec:
  repo: https://argoproj.github.io/argo-helm
  chart: argo-cd
  targetNamespace: argocd
  version: 9.1.0
  valuesContent: |-
    configs:
      params:
        server.insecure: true
        application.namespaces: "*"
      cm:
        url: https://argocd.home.arpa
        oidc.config: |
          name: Keycloak
          issuer: http://keycloak.home.arpa/realms/homelab
          clientID: argocd
          clientSecret: $argocd-oidc-secret:clientSecret
          requestedScopes: ["openid", "profile", "email", "groups"]
      rbac:
          policy.csv: |
            g, /admin, role:admin
            p, role:admin, *, *, *, allow
      secret:
        argocdServerAdminPassword: "$2a$12$hOSTGCskSOQwuIYLn5SnZOKFlGtykXcDiCXPa5Zue4S7ay2TdPxtW"
    server:
      extraArgs:
      - "--application-namespaces=*"
    controller:
      extraArgs:
      - "--application-namespaces=*"
    dex:
      enabled: false
    redis:
      enabled: false
    notifications:
      enabled: false
    externalRedis:
      host: redis-headless.storage.svc.cluster.local
      existingSecret: "argocd-redis-secret"
