apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: sealed-secrets
  targetNamespace: sealed-secrets
  version: 2.5.19
