apiVersion: v1
kind: Secret
metadata:
  name: example-cluster-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: example-cluster
  server: https://192.168.0.211:6443
  # change me
  config: |
    {
      "bearerToken": "<plaintext token>",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "<base64 encoded ca.crt>"
      }
    }
