apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: example-homelab-repository
  namespace: argocd
stringData:
  type: git
  url: https://forgejo.home.arpa/homelab/homelab.git
  password: changeme
  username: argo-bot
  project: example
  insecure: "true"
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: example-gitops
  namespace: argocd
stringData:
  type: git
  url: https://forgejo.home.arpa/example/gitops.git
  #url: https://gitlab.home.arpa/example/gitops.git
  password: changeme
  username: example-bot
  project: example
  insecure: "true"
type: Opaque
